FROM python:alpine
COPY . /app/backend
WORKDIR /app/backend
RUN pip install -r requirements.txt
RUN python manage.py collectstatic --noinput
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]